### PR TITLE
SortShuffleReader code refactor and improvement

### PR DESCRIPTION
**Pull request by jerryshao**
Hi @sryza , these days I looked through the Hadoop 2.4 MapReduce Merger related code and made some changes:
1. Extract and make the template for MergeThread.
2. Create two merge threads( in-memory merge thread and on-disk merge thread) for background merging. The merging strategy is the same as your PR, also the same as MR code.
3. For only 1 in-memory block to be merged, directly write to file without serde-compression code which did previously.
4. Fix `keyComparator` Integer overflow problem.
5. Add a `MixedShuffleReader` for both `HashShuffleReader` and `SortShuffleReader`. Only for shuffle with `keyOrdering` defined will go `SortShuffleReader` code path currently. (to be defined)

Would you mind taking a look at it and give me some comments. Thanks a lot.

### CODE REVIEW

**Comment by sryza** [comment]
I like the MixedShuffleReader.  A couple high level questions about the patch:

I'm wondering about the need for two merge threads.  My understanding is that, in MR, the reason we need use an InMemoryMerge thread to decouple the merging from the fetching threads.  In Spark, these are already decoupled (the fetching doesn't occur on the thread that's consuming the iterator of blocks). Are there other advantages to having an in-memory merge thread?

I think we should keep TieredDiskMerger separate from the SortShuffleReader.  My thinking is, that way, it should be easy for ExternalSorter to take advantage of it.

**Comment by jerryshao** [comment]
Hi Sandy, thanks  a lot for your comments.

I agree with you that in-memory merge thread is not necessary. I have no specific reason to do it, just for code consistency and decoupled from main `SortShuffleReader` thread.

Currently `TieredDiskMerger` is tightly coupled with `SortShuffleReader`, I know that `ExternalSorter` may also need this on-disk merger logic to control merge factor. I think unless we have a good solution to refactor `ExternalSorter`, I'd better to keep as it is.

Greatly appreciate your comments, do you have any other suggestions?

**Comment by sryza** [comment]
Keeping as is / holding not breaking out a TieredDiskMerger until we want to refactor ExternalSorter sounds reasonable to me.

I think having a separate inMemoryMerger thread that proceeds in lockstep with the main shuffle thread is kind of confusing from a code-readability and debugging standpoint.  I.e. if every time we do

```
    inMemoryMerger.startMerge(inMemoryBlocks)
    // We should wait until this merge is finished to release the memory
    inMemoryMerger.waitForMerge()
```

every time we spill, why not just call the spill directly?  From a glance, it leads to reader to think that some asynchronous processing would be going on, but, unless I'm misunderstanding, this isn't the case.

Either way, now that the Netty shuffle service is in, maybe it would be good to merge this patch, PR against Spark master, and continue discussion there?

**Comment by jerryshao** [comment]
Thanks a lot @sryza , I will follow your comments and do some modifications. Also I will run some benchmarks to see the performance difference compared to the previous code. Until all the things are done, I will submit a PR. Thanks a lot :).

**Comment by sryza** [comment]
Sounds good.  There's one additional change I think that could be worthwhile to make before benchmarking.  I'm worried about situations where the size of the data is only slightly larger than memory.  In that case, we'd end up spilling most of the data, instead of just the overflow.  We could avoid this by never spilling more data than the size of the outstanding unfetched data.  I can code this up after you make your update.

**Comment by jerryshao** [comment]
Hi @sryza , I just updated the code and made some small changes, you can check out the branch (https://github.com/jerryshao/apache-spark/tree/sort-shuffle-read-new-netty).

Besides I've run a round of SparkPerf's sortByKey  benchmark. Seems the performance is better than previous code, since we need not to spill data if memory is enough. But there has potential memory leakage when block transfer service changes to Netty, I have to dig into the details.

**Comment by sryza** [comment]
Awesome to hear that it's faster.  The updated branch looks good to me.  Will work on addressing the perf issue I mentioned earlier.  How do you feel about submitting what we have as a work-in-progress PR against master?

**Comment by jerryshao** [comment]
Hi Sandy, still have some bugs in testing against latest master branch, I will submit a WIP PR when some bugs are fixed. Thanks a lot.

**Pull request closed without merging**
